### ISSUE TITLE
Possibility to return superuser indication

### ISSUE THREAD

**Issue by teifip** [emqtt/emq_auth_http#2]
How is the plugin intended to be used in case the external authentication module has the knowledge of _normal_ users vs superusers?
I see that if the plugin receives a `4xx` reply to a `super_req`,  it immediately retries with a `auth_req`. This means that either the use of `super_req` is disabled, or the authentication of each _normal_ user will systematically cost two request-response rounds with the external module.
Would it be possible to just use `auth_req`, and have the indication of whether the user is a superuser or a _normal_ user in the response body?

**Comment by emqplus** [comment]
@teifip, just comment the '{super_req, [...]}' config.

**Comment by teifip** [comment]
@emqplus, thanks a lot! Commenting the `super_req` part is exactly what I'm doing now. Unfortunately, it prevents my external authentication module to report to `emqttd` whether the user is a superuser or a _normal_ user. In general, I expect to have plenty of _normal_ users and maximum one or two superusers. Therefore, support for superusers' authentication would be desirable without causing any performance penalty on the authentication of _normal_ users.

**Comment by huangdan** [comment]
@emqplus  the issue is implement
{emqttd_auth_http, [

    %% Variables: %u = username, %c = clientid, %a = ipaddress, %t = topic

    {super_req, [
      {method, post},
      {url, "http://localhost:8080/mqtt/superuser"},
      {params, [
        {username, "%u"},
        {clientid, "%c"}
      ]}
    ]},
